name: Build & Test
on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Bootstrap Vcpkg
        run: |
          cd vcpkg
          .\bootstrap-vcpkg.bat

      - name: Configure CMake
        run: |
          cmake -B build -S . `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -DBUILD_TESTS=ON `
            -DBUILD_KERNEL=OFF

      - name: Build
        run: cmake --build build --config Release

      - name: Run Unit Tests
        run: .\build\tests\Release\ChainOfTrust_Tests.exe
        continue-on-error: true
